name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        cache-provider: buildjet
    - name: Build
      run: cargo build --release
    - name: Pack
      run: |
        mkdir target/pingpong || rm -rf target/pingpong/*
        mv target/release/pingpong target/pingpong/pingpong
        cp -r config target/pingpong/config
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: pingpong.zip
        path: target/pingpong
