[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/aarch64-linux-gnu-gcc"
ar = "/usr/bin/aarch64-linux-gnu-ar"

[target.aarch64-unknown-linux-musl]
linker = "rust-lld"

[target.arm-unknown-linux-gnueabi]
linker = "rust-lld"

[target.armv7-unknown-linux-musleabihf]
linker = "rust-lld"

[target.i686-unknown-linux-musl]
linker = "rust-lld"
