[target.aarch64-unknown-linux-gnu]
linker = "rust-lld"

[target.aarch64-unknown-linux-musl]
linker = "rust-lld"

[target.arm-unknown-linux-gnueabi]
linker = "rust-lld"

[target.armv7-unknown-linux-musleabihf]
linker = "rust-lld"

[target.i686-unknown-linux-musl]
linker = "rust-lld"
